# Generated by Django 4.2.6 on 2023-10-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
