# Generated by Django 4.2.6 on 2023-10-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_delete_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='status',
            field=models.CharField(choices=[('Will go', 'Will go'), ("Won't go", "Won't go"), ('Still thinking...', 'Still thinking...')], max_length=55),
        ),
    ]
